---
version: '3'
services:
  mongodb:
    image: mongo:4.4
    hostname: mongodb
    container_name: mongodb
    #The Mongo-DB-Ports just need to be opened, when you run the backend app on localhost instead inside docker network
    ports:
      - 27017:27017
    #Define the Path to mount the Data of Database
    #volumes:
    #  - /data/mongodb:/data/db
  backend:
    build: ./backend
    hostname: backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
  frontend:
    build: ./frontend
    hostname: frontend
    container_name: frontend
    depends_on:
      - mongodb
      - backend
    ports:
      - "80:80"
    #  - "443:443"
    #Volume for cert-mount
    #volumes:
    #  - /etc/letsencrypt:/etc/letsencrypt