# generated by datamodel-codegen:
#   filename:  article.json
#   timestamp: 2022-05-24T18:25:55+00:00

from __future__ import annotations
from typing import List, Optional
from pydantic.dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class OldVersion():
    name: str
    text: str
    version: int

@dataclass
class Article():
    artikel_id: str
    artikel_name: str
    artikel_text: str
    created: str
    tags: List[str]
    current_versions: int
    old_versions: Optional[List[OldVersion]] = None

#Article.__pydantic_model__.update_forward_refs()
